import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :smtp_interceptor, SmtpInterceptorWeb.Endpoint,
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: ["http://localhost:4000/"]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: SmtpInterceptor.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :pique,
  auth: false,
  smtp_opts: [
    port: 4646,
  ],
  mail_handler: SmtpInterceptor.Handler,
  data_handler: SmtpInterceptor.Handler

config :smtp_interceptor, SmtpInterceptor.Mailer,
  adapter: Swoosh.Adapters.Local,
  level: :debug
